/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'DELL' at '18-5-23 下午7:51' with Gradle 2.14.1
 *
 * @author DELL, @date 18-5-23 下午7:51
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
